services:

  mysql:
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    networks:
      vpcbr:
        ipv4_address: "${VPC_SUBNET}.2"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: "${VPC_SUBNET}.2"
      PMA_USER: root
      UPLOAD_LIMIT: 256M
    networks:
      vpcbr:
        ipv4_address: "${VPC_SUBNET}.3"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      vpcbr:
        ipv4_address: "${VPC_SUBNET}.4"

  redis:
    image: redis
    container_name: redis
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      vpcbr:
        ipv4_address: "${VPC_SUBNET}.5"

  exim4:
    image: imixs/exim4
    container_name: exim4
    restart: always
    expose:
      - "25"
    environment:
      EXIM_SMARTHOST: "${EXIM_SMARTHOST}"
      EXIM_PASSWORD: "${EXIM_PASSWORD}"
      EXIM_ALLOWED_SENDERS: "0.0.0.0/0"
    networks:
      vpcbr:
        ipv4_address: "${VPC_SUBNET}.6"

  memcached:
    image: memcached
    container_name: memcached
    restart: always
    expose:
      - "11211"
    networks:
      vpcbr:
        ipv4_address: "${VPC_SUBNET}.7"

volumes:
  mongo-data:
  redis-data:
  mysql-data:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: "${VPC_SUBNET}.0/16"
         gateway: "${VPC_SUBNET}.1"