services:
  server:
    image: canebaycomputers/cbc:nginx-php8
    container_name: CONTAINER_NAME
    volumes:
      - .:/usr/share/nginx/html
      - /etc/hosts:/etc/hosts:ro
    networks:
      default:
        ipv4_address: IPV4_ADDRESS

networks:
  default:
    external: true
    name: docker-stack_STACK_ID_vpc
